### ISSUE TITLE
Allow rendering only an element

### ISSUE THREAD

**Issue by kurtisnelson** [ronen/rspec-page-regression#4]
It would be ideal to be able to do `expect(page.find("#thing")).to match_expectation` so that components can be isolated.

**Comment by ronen** [comment]
@kurtisnelson sounds intriguing -- but what would it do?  make all other elements invisible?  or render the page normally but then only grab the part of the image at that element's box?

In any case, I'm not likely to have time to work on it any time soon.  But I'm happy to accept a PR!

**Comment by kurtisnelson** [comment]
I'm actually working on a PR that makes the matcher take in an optional ignore: [left, top, right, bottom] box and not check for diffs there.
